Repository cceo-developer/sago-customer, pull requests merged in 2024-03, with the labels that each got.

#3 feat: ✨ add login functionality
  .env.example
  .gitignore
  index.html
  package-lock.json
  package.json
  src/assets/images/icono.png
  src/assets/images/logo.png
  src/const/asset.js
  src/layouts/AppLayout.vue
  src/layouts/AuthLayout.vue
  src/layouts/components/SidebarMenu.vue
  src/main.js
  src/router/auth/auth.js
  src/router/system/users.js
  src/views/auth/ForgotPassword.vue
  src/views/auth/Login.vue
  src/views/system/Profile.vue
  tailwind.config.js
Labels: :sparkles: new feature, ⏰ 5h

#4 feat (client id) ✨ added client id for customer
  .env.example
  src/views/auth/Login.vue
Labels: :bug: bug, :sparkles: new feature, ⏰ 0.5h

#5 feat (2FA Profile) ✨ added 2FA and profile functions
  .env.example
  package-lock.json
  package.json
  src/App.vue
  src/components/auth/TwoFactorAuth.vue
  src/components/widgets/ConfirmDeleteModal.vue
  src/components/widgets/ConfirmUpdateElementMessage.vue
  src/const/dateFormat.js
  src/const/larabug.js
  src/const/messageError.js
  src/const/primeVueOptions.js
  src/main.js
  src/pass_through/dialog.js
  src/pass_through/index.js
  src/pass_through/inputtext.js
  src/services/collaborator/users.js
  src/services/system/oauth-tokens.js
  src/views/auth/Login.vue
  src/views/system/Profile.vue
Labels: :sparkles: new feature, ⏰ 1h

#10 feat (syncfy data) ✨ added syncfy data for customers
  .env.example
  package-lock.json
  package.json
  src/components/Movements/Credentials/CredentialsActionButtons.vue
  src/components/Movements/Credentials/CredentialsTable.vue
  src/components/Movements/Credentials/CredentialsTableColumns.js
  src/components/Movements/Transactions/TransactionsBankTableColumns.js
  src/components/Movements/Transactions/TransactionsFiscalTableColumns.js
  src/components/Movements/Transactions/TransactionsTable.vue
  src/composables/tables.js
  src/const/can.js
  src/layouts/components/SidebarMenu.vue
  src/main.js
  src/router/index.js
  src/router/system/Movements.js
  src/services/collaborator/movements.js
  src/services/collaborator/users.js
  src/views/system/Movements/Accounts.vue
  src/views/system/Movements/BankMovements.vue
  src/views/system/Movements/FiscalMovements.vue
Labels: :sparkles: new feature, ⏰ 1.5h

#11 fix (firmed routes) :bug: validate firmed routes to redirect at dashboard when is login
  src/router/auth/auth.js
Labels: :bug: bug, ⏰ 0.5h

#13 feat (google analytics) ✨ added google analytics and bugs
  .env.example
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-testing.yml
  package-lock.json
  package.json
  src/components/Movements/Credentials/CredentialsTable.vue
  src/components/Movements/Credentials/CredentialsTableColumns.js
  src/components/Movements/Transactions/TransactionsBankTableColumns.js
  src/components/Movements/Transactions/TransactionsFiscalTableColumns.js
  src/layouts/components/SidebarMenu.vue
  src/router/system/users.js
  src/views/system/Profile.vue
  src/views/system/Users.vue
  vite.config.js
Labels: :bug: bug, :sparkles: new feature, ⏰ 6h
